name: Testes Cypress manuais

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório de testes (atual)
        uses: actions/checkout@v4

      - name: Clonar repositório da aplicação (backend)
        uses: actions/checkout@v4
        with:
          repository: edcaetanoguedes/telegram-api-backend
          token: ${{ secrets.GITHUB_TELEGRAM_API_TESTS_TOKEN }}
          path: telegram-api-backend
          ref: main

      - name: Instalar dependências da aplicação (backend)
        working-directory: telegram-api-backend
        run: npm ci

      - name: Iniciar aplicação em background
        working-directory: telegram-api-backend
        run: |
          npm start &

      - name: Esperar aplicação subir
        run: npx wait-on http://localhost:4000

      - name: Instalar dependências de testes (Cypress)
        run: npm ci

      - name: Rodar testes Cypress
        run: npm run test:cy:backend
