name: Testes Cypress manuais

on:
  workflow_dispatch:

jobs:
  backend-e2e-tests-automated:
    name: Testes Automatizados E2E (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório (backend)
        uses: actions/checkout@v4
        with:
          repository: edcaetanoguedes/telegram-api-backend # Ambos os repos deve estar na mesma conta/organização
          # Token da conta com permissões
          token: ${{ secrets.GH_TELEGRAM_API_TESTS_TOKEN }}
          # Define uma pasta com nome onde o repo será clonado
          # Bom pra quando se lida com mais de um projeto (ex: frontend, backend)
          path: telegram-api-backend
          # Define qual branch/tag será clonada
          ref: main


      - name: Instalar dependências da aplicação (backend)
        working-directory: telegram-api-backend
        run: npm ci

      - name: Iniciar aplicação em background
        working-directory: telegram-api-backend
        run: |
          npm start &

      - name: Esperar aplicação subir
        run: npx wait-on http://localhost:4000

      - name: Clonar repositório de testes (atual)
        uses: actions/checkout@v4

      - name: Instalar dependências de testes (Cypress)
        run: npm ci

      - name: Rodar testes Cypress
        run: npm run test:cy:all
